strata_base.settings:
  type: config_object
  label: 'Strata Base settings'
  mapping:
    restricted_content_types:
      type: sequence
      label: 'Restricted content types'
      sequence:
        type: string
        label: 'Content type machine name'
    notification_roles:
      type: sequence
      label: 'Notification roles'
      sequence:
        type: string
        label: 'Role machine name'
    notification_content_types:
      type: sequence
      label: 'Notification content types'
      sequence:
        type: string
        label: 'Content type machine name'
    notification_content_triggers:
      type: sequence
      label: 'Content notification triggers'
      sequence:
        type: string
        label: 'Trigger type'
    notification_comment_triggers:
      type: sequence
      label: 'Comment notification triggers'
      sequence:
        type: string
        label: 'Trigger type'
    notification_template_content_created_subject:
      type: string
      label: 'Content created email subject'
    notification_template_content_created_body:
      type: string
      label: 'Content created email body'
    notification_template_content_updated_subject:
      type: string
      label: 'Content updated email subject'
    notification_template_content_updated_body:
      type: string
      label: 'Content updated email body'
    notification_template_comment_created_subject:
      type: string
      label: 'Comment created email subject'
    notification_template_comment_created_body:
      type: string
      label: 'Comment created email body'
    notification_template_comment_updated_subject:
      type: string
      label: 'Comment updated email subject'
    notification_template_comment_updated_body:
      type: string
      label: 'Comment updated email body'
