strata_base.settings:
  type: config_object
  label: 'Strata Base settings'
  mapping:
    restricted_content_types:
      type: sequence
      label: 'Restricted content types'
      sequence:
        type: string
        label: 'Content type machine name'
    notification_roles:
      type: sequence
      label: 'Notification roles'
      sequence:
        type: string
        label: 'Role machine name'
    notification_content_types:
      type: sequence
      label: 'Notification content types'
      sequence:
        type: string
        label: 'Content type machine name'
    notification_content_triggers:
      type: sequence
      label: 'Content notification triggers'
      sequence:
        type: string
        label: 'Trigger type'
    notification_comment_triggers:
      type: sequence
      label: 'Comment notification triggers'
      sequence:
        type: string
        label: 'Trigger type'
