# Schema for the_strata_theme settings.

the_strata_theme.settings:
  type: theme_settings
  label: 'The Strata Theme settings'
  mapping:
    preset_accent_color:
      type: string
      label: 'Preset accent color'
    preset_focus_color:
      type: string
      label: 'Preset focus color'
    enable_darkmode:
      type: string
      label: 'The darkmode'
    classic_toolbar:
      type: string
      label: 'The classic toolbar'
    secondary_toolbar_frontend:
      type: boolean
      label: 'Secondary toolbar in Frontend'
    high_contrast_mode:
      type: boolean
      label: 'High contrast mode'
    accent_color:
      type: string
      label: 'The accent color'
    focus_color:
      type: string
      label: 'The focus color'
    layout_density:
      type: string
      label: 'Layout density'
    show_description_toggle:
      type: boolean
      label: 'Display help icon to toggle form description'
    show_user_theme_settings:
      type: boolean
      label: 'Let user override theme'
    sticky_action_buttons:
      type: boolean
      label: 'Sticky action buttons'
