name: strata
type: drupal
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.6"
nodejs_version: "20"
corepack_enable: false
composer_version: "2"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
timezone: UTC
web_environment: []
hooks:
  post-start:
    - exec: composer install
